// @format

export const simple = {
	void: {
		'1-2': { color: 'red', number: 1 },
		'1-7': { color: 'yellow', number: 3 },
		'1-10': { color: 'red', number: 6 },
		'1-12': { color: 'cyan', number: 3 },
		'2-4': { color: 'green', number: 2 },
		'2-5': { color: 'yellow', number: 2 },
		'2-6': { color: 'cyan', number: 1 },
		'2-7': { color: 'yellow', number: 6 },
		'2-9': { color: 'purple', number: 5 },
		'3-3': { color: 'green', number: 7 },
		'4-6': { color: 'blue', number: 4 },
		'4-8': { color: 'white', number: 5 },
		'4-9': { color: 'yellow', number: 1 },
		'5-6': { color: 'red', number: 5 },
		'5-9': { color: 'purple', number: 7 },
		'6-5': { color: 'purple', number: 1 },
		'6-9': { color: 'white', number: 7 },
		'6-11': { color: 'cyan', number: 4 },
		'7-2': { color: 'white', number: 6 },
		'7-4': { color: 'green', number: 5 },
		'7-9': { color: 'yellow', number: 4 },
		'7-12': { color: 'blue', number: 5 },
		'8-4': { color: 'cyan', number: 2 },
		'8-5': { color: 'cyan', number: 7 },
		'8-10': { color: 'red', number: 3 },
		'8-12': { color: 'cyan', number: 6 },
		'9-3': { color: 'green', number: 3 },
		'9-7': { color: 'purple', number: 4 },
		'9-9': { color: 'purple', number: 2 },
		'10-2': { color: 'white', number: 2 },
		'10-3': { color: 'green', number: 4 },
		'10-5': { color: 'blue', number: 2 },
		'10-12': { color: 'green', number: 6 },
		'11-1': { color: 'blue', number: 6 },
		'11-6': { color: 'red', number: 7 },
		'11-7': { color: 'purple', number: 3 },
		'11-11': { color: 'blue', number: 3 },
		'12-2': { color: 'cyan', number: 5 },
	},
}

export const secondary = {
	void: {
		'2': {
			'1-1-2-12': { color: 'white', number: 1 },
			'1-1-4-5': { color: 'red', number: 2 },
			'4-3-2-4': { color: 'green', number: 1 },
			'4-3-2-11': { color: 'purple', number: 6 },
			'8-6-2-9': { color: 'white', number: 3 },
			'8-6-9-2': { color: 'yellow', number: 5 },
			'11-4-2-8': { color: 'blue', number: 7 },
			'11-4-4-11': { color: 'yellow', number: 7 },
			'11-4-5-4': { color: 'red', number: 4 },
			'12-5-7-1': { color: 'white', number: 4 },
			'12-5-12-11': { color: 'blue', number: 1 },
		},

		'3': {
			'1-1-8-10': { color: 'white', number: 1 },
			'1-1-6-5': { color: 'red', number: 2 },
			'4-3-2-9': { color: 'green', number: 1 },
			'4-3-4-7': { color: 'purple', number: 6 },
			'8-6-2-10': { color: 'white', number: 3 },
			'8-6-12-12': { color: 'yellow', number: 5 },
			'11-4-4-8': { color: 'blue', number: 7 },
			'11-4-12-3': { color: 'yellow', number: 7 },
			'11-4-7-6': { color: 'red', number: 4 },
			'12-5-5-7': { color: 'white', number: 4 },
			'12-5-4-4': { color: 'blue', number: 1 },
		},
	},
}
